/**
 * 异常代码常量定义
 *
 * @description 定义所有领域异常的代码常量
 * 提供统一的异常代码管理，便于异常处理和监控
 *
 * @since 1.0.0
 */

/**
 * 用户相关异常代码
 */
export const USER_EXCEPTION_CODES = {
  // 用户状态异常
  USER_NOT_PENDING: 'USER_NOT_PENDING',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
  USER_NOT_LOCKED: 'USER_NOT_LOCKED',
  USER_NOT_SUSPENDED: 'USER_NOT_SUSPENDED',
  USER_NOT_DISABLED: 'USER_NOT_DISABLED',
  INVALID_USER_STATUS: 'INVALID_USER_STATUS',
  
  // 用户验证异常
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_PHONE: 'INVALID_PHONE',
  
  // 用户业务规则异常
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_USERNAME_ALREADY_EXISTS: 'USER_USERNAME_ALREADY_EXISTS',
  USER_PHONE_ALREADY_EXISTS: 'USER_PHONE_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  
  // 用户操作异常
  INVALID_SUSPENSION_REASON: 'INVALID_SUSPENSION_REASON',
  INVALID_DISABLE_REASON: 'INVALID_DISABLE_REASON',
  INVALID_LOCK_REASON: 'INVALID_LOCK_REASON',
  USER_ALREADY_ACTIVE: 'USER_ALREADY_ACTIVE',
  USER_ALREADY_SUSPENDED: 'USER_ALREADY_SUSPENDED',
  USER_ALREADY_DISABLED: 'USER_ALREADY_DISABLED',
  USER_ALREADY_LOCKED: 'USER_ALREADY_LOCKED',
} as const;

/**
 * 租户相关异常代码
 */
export const TENANT_EXCEPTION_CODES = {
  // 租户状态异常
  TENANT_NOT_PENDING: 'TENANT_NOT_PENDING',
  TENANT_NOT_ACTIVE: 'TENANT_NOT_ACTIVE',
  TENANT_NOT_SUSPENDED: 'TENANT_NOT_SUSPENDED',
  TENANT_NOT_DISABLED: 'TENANT_NOT_DISABLED',
  INVALID_TENANT_STATUS: 'INVALID_TENANT_STATUS',
  
  // 租户验证异常
  INVALID_TENANT_NAME: 'INVALID_TENANT_NAME',
  INVALID_TENANT_CODE: 'INVALID_TENANT_CODE',
  INVALID_TENANT_TYPE: 'INVALID_TENANT_TYPE',
  INVALID_ADMIN_ID: 'INVALID_ADMIN_ID',
  
  // 租户业务规则异常
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_ALREADY_EXISTS: 'TENANT_ALREADY_EXISTS',
  TENANT_CODE_ALREADY_EXISTS: 'TENANT_CODE_ALREADY_EXISTS',
  INVALID_UPGRADE: 'INVALID_UPGRADE',
  
  // 租户操作异常
  INVALID_SUSPENSION_REASON: 'INVALID_SUSPENSION_REASON',
  INVALID_DISABLE_REASON: 'INVALID_DISABLE_REASON',
  TENANT_ALREADY_ACTIVE: 'TENANT_ALREADY_ACTIVE',
  TENANT_ALREADY_SUSPENDED: 'TENANT_ALREADY_SUSPENDED',
  TENANT_ALREADY_DISABLED: 'TENANT_ALREADY_DISABLED',
  
  // 租户资源异常
  TENANT_RESOURCE_LIMIT_EXCEEDED: 'TENANT_RESOURCE_LIMIT_EXCEEDED',
  INVALID_RESOURCE_LIMITS: 'INVALID_RESOURCE_LIMITS',
  INVALID_TENANT_CONFIG: 'INVALID_TENANT_CONFIG',
} as const;

/**
 * 授权相关异常代码
 */
export const AUTHORIZATION_EXCEPTION_CODES = {
  // 角色状态异常
  ROLE_NOT_ACTIVE: 'ROLE_NOT_ACTIVE',
  ROLE_NOT_INACTIVE: 'ROLE_NOT_INACTIVE',
  INVALID_ROLE_STATUS: 'INVALID_ROLE_STATUS',
  
  // 角色验证异常
  INVALID_ROLE_NAME: 'INVALID_ROLE_NAME',
  INVALID_ROLE_CODE: 'INVALID_ROLE_CODE',
  INVALID_DESCRIPTION: 'INVALID_DESCRIPTION',
  
  // 角色业务规则异常
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ALREADY_EXISTS: 'ROLE_ALREADY_EXISTS',
  ROLE_CODE_ALREADY_EXISTS: 'ROLE_CODE_ALREADY_EXISTS',
  SYSTEM_ROLE_MODIFICATION: 'SYSTEM_ROLE_MODIFICATION',
  
  // 角色操作异常
  PERMISSION_ALREADY_EXISTS: 'PERMISSION_ALREADY_EXISTS',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  PARENT_ROLE_ALREADY_EXISTS: 'PARENT_ROLE_ALREADY_EXISTS',
  PARENT_ROLE_NOT_FOUND: 'PARENT_ROLE_NOT_FOUND',
  CIRCULAR_INHERITANCE: 'CIRCULAR_INHERITANCE',
  
  // 权限异常
  INVALID_PERMISSION: 'INVALID_PERMISSION',
  INVALID_PERMISSION_LEVEL: 'INVALID_PERMISSION_LEVEL',
  SYSTEM_PERMISSION_MODIFICATION: 'SYSTEM_PERMISSION_MODIFICATION',
  
  // 用户角色异常
  INVALID_EXPIRATION: 'INVALID_EXPIRATION',
  USER_ROLE_ALREADY_EXISTS: 'USER_ROLE_ALREADY_EXISTS',
  USER_ROLE_NOT_FOUND: 'USER_ROLE_NOT_FOUND',
} as const;

/**
 * 组织相关异常代码
 */
export const ORGANIZATION_EXCEPTION_CODES = {
  // 组织状态异常
  ORGANIZATION_NOT_PENDING: 'ORGANIZATION_NOT_PENDING',
  ORGANIZATION_NOT_ACTIVE: 'ORGANIZATION_NOT_ACTIVE',
  INVALID_ORGANIZATION_STATUS: 'INVALID_ORGANIZATION_STATUS',
  
  // 组织验证异常
  INVALID_ORGANIZATION_NAME: 'INVALID_ORGANIZATION_NAME',
  INVALID_ORGANIZATION_CODE: 'INVALID_ORGANIZATION_CODE',
  INVALID_ADMIN_ID: 'INVALID_ADMIN_ID',
  
  // 组织业务规则异常
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  ORGANIZATION_ALREADY_EXISTS: 'ORGANIZATION_ALREADY_EXISTS',
  ORGANIZATION_CODE_ALREADY_EXISTS: 'ORGANIZATION_CODE_ALREADY_EXISTS',
  
  // 组织操作异常
  INVALID_SUSPENSION_REASON: 'INVALID_SUSPENSION_REASON',
  INVALID_DISABLE_REASON: 'INVALID_DISABLE_REASON',
  INVALID_ARCHIVE_REASON: 'INVALID_ARCHIVE_REASON',
  ORGANIZATION_ALREADY_ACTIVE: 'ORGANIZATION_ALREADY_ACTIVE',
  ORGANIZATION_ALREADY_SUSPENDED: 'ORGANIZATION_ALREADY_SUSPENDED',
  ORGANIZATION_ALREADY_DISABLED: 'ORGANIZATION_ALREADY_DISABLED',
  
  // 部门管理异常
  INVALID_DEPARTMENT_ID: 'INVALID_DEPARTMENT_ID',
  DEPARTMENT_ALREADY_MANAGED: 'DEPARTMENT_ALREADY_MANAGED',
  DEPARTMENT_NOT_MANAGED: 'DEPARTMENT_NOT_MANAGED',
} as const;

/**
 * 部门相关异常代码
 */
export const DEPARTMENT_EXCEPTION_CODES = {
  // 部门状态异常
  DEPARTMENT_NOT_PENDING: 'DEPARTMENT_NOT_PENDING',
  DEPARTMENT_NOT_ACTIVE: 'DEPARTMENT_NOT_ACTIVE',
  INVALID_DEPARTMENT_STATUS: 'INVALID_DEPARTMENT_STATUS',
  
  // 部门验证异常
  INVALID_DEPARTMENT_NAME: 'INVALID_DEPARTMENT_NAME',
  INVALID_DEPARTMENT_CODE: 'INVALID_DEPARTMENT_CODE',
  INVALID_DEPARTMENT_LEVEL: 'INVALID_DEPARTMENT_LEVEL',
  INVALID_ADMIN_ID: 'INVALID_ADMIN_ID',
  
  // 部门业务规则异常
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT_NOT_FOUND',
  DEPARTMENT_ALREADY_EXISTS: 'DEPARTMENT_ALREADY_EXISTS',
  DEPARTMENT_CODE_ALREADY_EXISTS: 'DEPARTMENT_CODE_ALREADY_EXISTS',
  
  // 部门操作异常
  INVALID_SUSPENSION_REASON: 'INVALID_SUSPENSION_REASON',
  INVALID_DISABLE_REASON: 'INVALID_DISABLE_REASON',
  INVALID_ARCHIVE_REASON: 'INVALID_ARCHIVE_REASON',
  DEPARTMENT_ALREADY_ACTIVE: 'DEPARTMENT_ALREADY_ACTIVE',
  DEPARTMENT_ALREADY_SUSPENDED: 'DEPARTMENT_ALREADY_SUSPENDED',
  DEPARTMENT_ALREADY_DISABLED: 'DEPARTMENT_ALREADY_DISABLED',
  
  // 部门层级异常
  DEPARTMENT_HIERARCHY_ERROR: 'DEPARTMENT_HIERARCHY_ERROR',
  INVALID_PARENT_DEPARTMENT: 'INVALID_PARENT_DEPARTMENT',
  CIRCULAR_DEPARTMENT_HIERARCHY: 'CIRCULAR_DEPARTMENT_HIERARCHY',
} as const;

/**
 * 值对象相关异常代码
 */
export const VALUE_OBJECT_EXCEPTION_CODES = {
  // 通用值对象异常
  INVALID_VALUE_OBJECT: 'INVALID_VALUE_OBJECT',
  VALUE_OBJECT_VALIDATION_FAILED: 'VALUE_OBJECT_VALIDATION_FAILED',
  
  // 特定值对象异常
  INVALID_USER_PROFILE: 'INVALID_USER_PROFILE',
  INVALID_TENANT_ID: 'INVALID_TENANT_ID',
  INVALID_TENANT_CONFIG: 'INVALID_TENANT_CONFIG',
  INVALID_RESOURCE_LIMITS: 'INVALID_RESOURCE_LIMITS',
  INVALID_DEPARTMENT_LEVEL: 'INVALID_DEPARTMENT_LEVEL',
  INVALID_PERMISSION: 'INVALID_PERMISSION',
} as const;

/**
 * 多租户相关异常代码
 */
export const MULTI_TENANCY_EXCEPTION_CODES = {
  // 跨租户操作异常
  CROSS_TENANT_OPERATION: 'CROSS_TENANT_OPERATION',
  TENANT_CONTEXT_ERROR: 'TENANT_CONTEXT_ERROR',
  INVALID_TENANT_CONTEXT: 'INVALID_TENANT_CONTEXT',
  
  // 租户隔离异常
  TENANT_ISOLATION_VIOLATION: 'TENANT_ISOLATION_VIOLATION',
  UNAUTHORIZED_TENANT_ACCESS: 'UNAUTHORIZED_TENANT_ACCESS',
} as const;

/**
 * 事件相关异常代码
 */
export const EVENT_EXCEPTION_CODES = {
  // 事件流异常
  EVENT_STREAM_ERROR: 'EVENT_STREAM_ERROR',
  EMPTY_EVENT_STREAM: 'EMPTY_EVENT_STREAM',
  INVALID_EVENT_STREAM: 'INVALID_EVENT_STREAM',
  
  // 事件处理异常
  EVENT_HANDLING_ERROR: 'EVENT_HANDLING_ERROR',
  EVENT_PUBLISHING_ERROR: 'EVENT_PUBLISHING_ERROR',
  EVENT_SUBSCRIPTION_ERROR: 'EVENT_SUBSCRIPTION_ERROR',
} as const;

/**
 * 所有异常代码的联合类型
 */
export type ExceptionCode = 
  | typeof USER_EXCEPTION_CODES[keyof typeof USER_EXCEPTION_CODES]
  | typeof TENANT_EXCEPTION_CODES[keyof typeof TENANT_EXCEPTION_CODES]
  | typeof AUTHORIZATION_EXCEPTION_CODES[keyof typeof AUTHORIZATION_EXCEPTION_CODES]
  | typeof ORGANIZATION_EXCEPTION_CODES[keyof typeof ORGANIZATION_EXCEPTION_CODES]
  | typeof DEPARTMENT_EXCEPTION_CODES[keyof typeof DEPARTMENT_EXCEPTION_CODES]
  | typeof VALUE_OBJECT_EXCEPTION_CODES[keyof typeof VALUE_OBJECT_EXCEPTION_CODES]
  | typeof MULTI_TENANCY_EXCEPTION_CODES[keyof typeof MULTI_TENANCY_EXCEPTION_CODES]
  | typeof EVENT_EXCEPTION_CODES[keyof typeof EVENT_EXCEPTION_CODES];